# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# development API_key: df8effbc5e0caf32832a5353cf2620be
# development url: http://localhost:3000/api/v1/locations?access_token=df8effbc5e0caf32832a5353cf2620be

development:
  secret_key_base: cb1add585c3d8dd1538f91db802d11af86bfbd9089818bd88c56364a5078f8c7561fd15b9018220b3c04786678c492db7b57f507e5bf5baa87cc4473d41d54c0

test:
  secret_key_base: e024ccac78e6923a15d73a9dcd8b5bf6f326bd4c7a099393f73b143c57ba1741a8edfb62421337a1ae24e6e2fdb19a2ae1e10dfb323218128f1cadf75d26d7cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

